import Image from 'next/image'
import Head from 'next/head'

import Navbar from '../components/navbar'

import logo from '../public/images/backgrounds/logo.gif'

import assetOne from '../public/images/assets/001.png'
import assetTwo from '../public/images/assets/002.png'
import assetThree from '../public/images/assets/003.png'
import assetFour from '../public/images/assets/004.png'

import potionOne from '../public/images/potion/001.jpg'
import potionTwo from '../public/images/potion/002.jpg'
import potionThree from '../public/images/potion/003.jpg'
import potionFour from '../public/images/potion/004.jpg'
import potionFive from '../public/images/potion/005.jpg'
import potionSix from '../public/images/potion/006.jpg'
import potionSeven from '../public/images/potion/007.jpg'
import potionEight from '../public/images/potion/008.jpg'
import potionNine from '../public/images/potion/009.jpg'


export default function shop() {


  const nftOption = () => {
    let shop_nft = document.getElementById('nft-shop_container');
    let shop_potion = document.getElementById('potions-shop_container');

    let nft = document.getElementById('nft');
    let potion = document.getElementById('potion');

    nft.classList.add('aside-active')
    potion.classList.remove('aside-active')

    //Add potions shop
    shop_nft.classList.remove('none');
    shop_potion.classList.add('none');
  }

  const potionsOption = () => {
    let shop_nft = document.getElementById('nft-shop_container');
    let shop_potion = document.getElementById('potions-shop_container');

    let nft = document.getElementById('nft');
    let potion = document.getElementById('potion');

    nft.classList.remove('aside-active');
    potion.classList.add('aside-active');

    //Add potions shop
    shop_nft.classList.add('none');
    shop_potion.classList.remove('none');
  }


  return (
    
  <main>
    <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Navbar
        classShop="nav-active"
      />

      <div className="container-love">
        <div className="text-container">
          <h1>Spend some $LOVE</h1>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officia velit deleniti excepturi aliquid libero deserunt molestias quae, sequi, atque, modi cum quo. Voluptates, laboriosam repudiandae blanditiis esse similique.</p>
        </div>
    </div>
        <div className="container-flex">
          <aside>
            <li onClick={nftOption} id="nft" className="aside-active">NFTs</li>
            <li>Whitelist Passes</li>
            <li>Merchandise</li>
            <li>Real World Things</li>
            <li onClick={potionsOption} id="potion">Love Potions</li>
          </aside>

          <section id="nft-shop_container" className="nft-container">
            <div className="nft-item">
              <Image src={assetOne} alt=""/>
              <h5>NFT name</h5>

              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>2000 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={assetTwo} alt=""/>
              <h5>NFT name</h5>

              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>2000 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
            <Image src={assetThree} alt=""/>
              <h5>NFT name</h5>

              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>2000 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
            <Image src={assetFour} alt=""/>
              <h5>NFT name</h5>

              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>2000 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
            <Image src={assetOne} alt=""/>
              <h5>NFT name</h5>

              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>2000 $LOVE</p>
              </div>
            </div>
          </section>

          <section id="potions-shop_container" className="nft-container none">
            <div className="nft-item">
              <Image src={potionOne} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>300 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionTwo} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>300 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionThree} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>300 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionFour} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>300 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionFive} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>300 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionSix} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>300 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionSeven} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>600 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionEight} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>600 $LOVE</p>
              </div>
            </div>
            <div className="nft-item">
              <Image src={potionNine} alt=""/>
              <h5>NFT name</h5>
              <div className="button-price">
                <button className="button-buy">Buy now</button>
                <p>900 $LOVE</p>
              </div>
            </div>
          </section>
        </div>
    </main >
  )
}
